name: docs_experience
dependencies:
  over_react: ">=3.0.0 <=3.1.0"
  react: 5.0.0

dev_dependencies:
  build_runner:
  build_test:
  build_web_compilers:

dependency_overrides:
  shell_events:
    path: ../shell_events
